// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: data.proto

package data

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// Для регистрации клиента
type Module struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Module) Reset()         { *m = Module{} }
func (m *Module) String() string { return proto.CompactTextString(m) }
func (*Module) ProtoMessage()    {}
func (*Module) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}
func (m *Module) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Module.Unmarshal(m, b)
}
func (m *Module) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Module.Marshal(b, m, deterministic)
}
func (m *Module) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Module.Merge(m, src)
}
func (m *Module) XXX_Size() int {
	return xxx_messageInfo_Module.Size(m)
}
func (m *Module) XXX_DiscardUnknown() {
	xxx_messageInfo_Module.DiscardUnknown(m)
}

var xxx_messageInfo_Module proto.InternalMessageInfo

func (m *Module) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Module) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

// Ответ регистрации клиента
type ModuleResp struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Uri                  string   `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	UriClient            string   `protobuf:"bytes,3,opt,name=uri_client,json=uriClient,proto3" json:"uri_client,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModuleResp) Reset()         { *m = ModuleResp{} }
func (m *ModuleResp) String() string { return proto.CompactTextString(m) }
func (*ModuleResp) ProtoMessage()    {}
func (*ModuleResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1}
}
func (m *ModuleResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleResp.Unmarshal(m, b)
}
func (m *ModuleResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleResp.Marshal(b, m, deterministic)
}
func (m *ModuleResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleResp.Merge(m, src)
}
func (m *ModuleResp) XXX_Size() int {
	return xxx_messageInfo_ModuleResp.Size(m)
}
func (m *ModuleResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleResp.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleResp proto.InternalMessageInfo

func (m *ModuleResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *ModuleResp) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *ModuleResp) GetUriClient() string {
	if m != nil {
		return m.UriClient
	}
	return ""
}

func init() {
	proto.RegisterType((*Module)(nil), "data.Module")
	proto.RegisterType((*ModuleResp)(nil), "data.ModuleResp")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0x2c, 0x49,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x0c, 0xb8, 0xd8, 0x7c, 0xf3,
	0x53, 0x4a, 0x73, 0x52, 0x85, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18,
	0x35, 0x38, 0x83, 0xc0, 0x6c, 0x90, 0x58, 0x49, 0x65, 0x41, 0xaa, 0x04, 0x13, 0x44, 0x0c, 0xc4,
	0x56, 0x0a, 0xe6, 0xe2, 0x82, 0xe8, 0x08, 0x4a, 0x2d, 0x2e, 0x10, 0x12, 0xe1, 0x62, 0x4d, 0x2d,
	0x2a, 0xca, 0x2f, 0x82, 0x6a, 0x83, 0x70, 0x84, 0x04, 0xb8, 0x98, 0x4b, 0x8b, 0x32, 0xa1, 0xda,
	0x40, 0x4c, 0x21, 0x59, 0x2e, 0xae, 0xd2, 0xa2, 0xcc, 0xf8, 0xe4, 0x9c, 0xcc, 0xd4, 0xbc, 0x12,
	0x09, 0x66, 0xb0, 0x04, 0x67, 0x69, 0x51, 0xa6, 0x33, 0x58, 0x20, 0x89, 0x0d, 0xec, 0x26, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x81, 0x8b, 0x28, 0xb4, 0xa1, 0x00, 0x00, 0x00,
}
